openapi: "3.0.0"

info:
  title: Service example
  version: "1.0.0"
servers:
  - url: http://localhost:8080
    description: Local server

paths:
    '/example':
      get:
        responses:
          200:
            description: OK
            content:
              text/plain:
                schema:
                  type: string
      post:
        responses:
          200:
            description: OK
            content:
              text/plain:
                schema:
                  type: string
    '/example/{id}':
      get:
        parameters:
          - name: id
            in: path
            required: true
            schema:
              type: string
        responses:
          200:
            description: OK
            content:
              text/plain:
                schema:
                  type: string
